<?xml version="1.0" encoding="utf-8"?><Database Name="projectXService" Class="projectXLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-VUH2K375\SQLEXPRESS;Initial Catalog=projectXService;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="projectXServiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WeekDaysScore" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WeekendScore" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalScore" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionsAndAnswers" Member="QuestionsAndAnswers">
    <Type Name="QuestionsAndAnswer">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Diagram" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TimeInSeconds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post">
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Diagram" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>